### ISSUE TITLE
Option to disable Create Island message if "Automatic Create Island" is on

### ISSUE THREAD

**Issue by Biochao** [Bartz24/VoidIslandControl#11]
Doesn't make much sense to inform the player to create an island if one is already created for them.

**Comment by Bartz24** [comment]
Yup, it's already on my list to add to the next update. (Want to wait as it's kinda minor)
:D
Well, I'll just disable the message as it won't be usable anyway

**Comment by Bartz24** [comment]
Added to next version. well, not the config, i just disabled it
