### ISSUE TITLE
Crash entering nether 

### ISSUE THREAD

**Issue by cauliflower69** [Bartz24/VoidIslandControl#13]
https://pastebin.com/NsKmv5Am

When a player attempts to go the nether the server crashes

**Comment by Bartz24** [comment]
what version of the mod and mc?

**Comment by cauliflower69** [comment]
voidislandcontrol-1.1.7

1.11.2

**Comment by Bartz24** [comment]
this version is unsupported, sorry.
i think i fixed the issue in 1.12 though
