### ISSUE TITLE
[Enhancement] A better starting spawn island.

### ISSUE THREAD

**Issue by kreezxil** [Bartz24/VoidIslandControl#14]
Currently you have it as bedrock.

That tells me two things:
1. You aren't sure how to protect the spawn.
1. Bedrock is the only thing a non-creative player can not destroy.

However bedrock is ugly and you take away the chance to give starting information about the mod and world that players are spawned into. Yes you have the press 'G' thing, but that's not always reliable if a pack dev allows a mod into their system that overrides the 'G' key.

Solution build a nice spawn island that has signs and stuff explaining how to get started in the mod. Or examples of things with signs on them saying on what page of the guide they are found.

And put this following code from my new "[No Op Spawn Protection](https://minecraft.curseforge.com/projects/no-op-spawn-protection)" mod in your mod:
```java
    @SubscribeEvent
    public static PlayerInteractEvent escapingSpawn(PlayerInteractEvent event) {
    	EntityPlayer player = event.getEntityPlayer();
    	World world = player.getEntityWorld();
    	int px,pz,wx,wz;
    	
    	px = player.getPosition().getX();
    	pz = player.getPosition().getZ();
    	wx = world.getSpawnPoint().getX();
    	wz = world.getSpawnPoint().getZ();
    	
    	if(px > wx + Config.spawnProtection ||
    	   pz > wz + Config.spawnProtection ||
    	   px < wx - Config.spawnProtection ||
    	   pz < wz - Config.spawnProtection) {
    		return event;
    	} else {
    		if(!player.isCreative() && event.isCancelable()) {
    			event.setCanceled(true);
    		}
    		return null;
    	}
   }
```
src: https://github.com/kreezxil/spawnprotection/blob/master/src/main/java/com/kreezcraft/spawnprotection/CommonProxy.java#L45-L67

Notes: I'm aware that this type of protection only allows creatives to interact with spawn. Which means no button pushing, door opening, looking in chests. But that can be easily remedied.

**Comment by ghost** [comment]
He can also transform the bedrock block in a infinite dirt block, when the player break it, the dirt block respawn ( and its very useful for the skyblock maps !

**Comment by Bartz24** [comment]
I'll think about this, and how I want to handle it. Not going to happen right now though

**Comment by kreezxil** [comment]
woah, 27 days to respond.

**Comment by Bartz24** [comment]
Spawn protection has been added based on kreezxil's code!
