### ISSUE TITLE
Voiding Dimensions on a Whitelist basis in Configs

### ISSUE THREAD

**Issue by Vyraal1** [Bartz24/VoidIslandControl#20]
Would it be possible to have Void Island Control have a config that takes integers/DIM ID's to whitelist the voiding of dimensions? The current system has a boolean for Nether/End/Overworld, and it seems to be voiding a custom made dimension with JED.

**Comment by Bartz24** [comment]
Voiding will only be used in dimension -1 and 1 now
I'll let other mods handle which dims get voided aside from the vanilla ones
