### ISSUE TITLE
voidisland control and SpongeForge

### ISSUE THREAD

**Issue by Whazaaaaa** [Bartz24/VoidIslandControl#22]
Hello!

I was wondering if you could take a look at an issue I was having with SpongeForge
https://github.com/SpongePowered/SpongeForge/issues/1861

In short. A player has to reconnect 2 times when they go to the nether for example. And their connection with plugins for sponge is gone in that time.

I tried fixing it with them, but they seem to think it can be fixed better on your end. SpongeForge is a pluginmanager for forge, which is really helpfull for running servers. If you could take a look at this and fix it for 1.3 that would be amazing.

Thank you.

**Comment by Bartz24** [comment]
The nether teleportation code has been removed
