### ISSUE TITLE
Suggestion: Ability to disable the overriding of the default world selected at world creation

### ISSUE THREAD

**Issue by TeetoKaziim** [Bartz24/VoidIslandControl#23]
So this is a strange use case, but I'm using your mod specifically for the feature of having a 1:1 ratio between the nether and the overworld. But the pack isn't really a skyblock. At present, I'm using "Default World Generator Port" to bully the default worldtype into something other than "Void? World", and this is working.

But, I'm gonna be super selfish and suggest either a config to disable the default world type selecting, or, for ultimate selfishness, a seperate mod that is just your 1:1 ratio nether. Even though it would probably only ever get 1 download (me).

Still, thankyou for this mod, and I'm getting by even as things are, but I thought I'd throw it out there. The best to ya.

**Comment by Bartz24** [comment]
The 1:1 Nether is being removed in the next version...sorry. It's caused too many issues. It might come back as a feature later on once I understand how minecraft/forge code more.

**Comment by TeetoKaziim** [comment]
Nah I understand. Best of luck!
