### ISSUE TITLE
[Suggestion] Dimensional Configs for Applying Void Island Controls?

### ISSUE THREAD

**Issue by Vyraal1** [Bartz24/VoidIslandControl#24]
Hey, so you're mod's pretty unique in that it's the only one that auto-generates an islands for new players, making it vital for multiplayer servers with maps that start on a skyblock. My pack starts off at a skyblock, and has the player travel to different dimensions, however due to some mod incompats, I had to make the starter dimension in dim 100, and leave the Dim 0 as a normal overworld so that I can get the appropriate world generation to spawn. 

As a result though, I don't have access to the features from VIC such as the auto generating islands for each player, is there a way to make this work in other dimensions than Dim 0?

**Comment by Bartz24** [comment]
I'll add this to my to-do list, but it'll take a bit as a lot of the mod is based on it being in dimension 0

**Comment by Bartz24** [comment]
Added a config for this in today's update
