### ISSUE TITLE
[Suggestion] Ability to set spawn offset per island type as opposed to globally.

### ISSUE THREAD

**Issue by MrNinja93** [Bartz24/VoidIslandControl#25]
Trying to make a custom island which happens to be somewhat larger and in two parts so it's spawnpoint needs to be offset. 

However, in doing so I'm noticing it applies globally to all other island types including spawn so players on world load fall into the void and die, not sure how feasible it'd be but an option to apply offset per island or blacklist it from offsetting islands you don't need it on would be great.

**Comment by Bartz24** [comment]
This is now possible in the 1.4 versions
