### ISSUE TITLE
Bedrock Bug

### ISSUE THREAD

**Issue by Winddbourne** [Bartz24/VoidIslandControl#3]
Getting rid of bedrock doesn't put anything there to replace it and if you start on the wood island you fall through the water and die; if you start on the sand island the sand updates and the entire island falls into the void. 

I disabled the water for now on the wooden platform and am temporarily disabling the sand platform until we can get a fix.  In other areas of the config you have options to replace a filler block of some sort with air or some other block. Using the same technique bedrock could be the default block for a layer and instead of disabling it and causing issues we could replace it with stone or some other floating block.

**Comment by Bartz24** [comment]
Added a config to replace bedrock in 1.0.5 with a secondary block
