### ISSUE TITLE
creating world type 

### ISSUE THREAD

**Issue by drmorgmd** [Bartz24/VoidIslandControl#31]
so i am working on a modpack (1.12.2) and i wanted to make a deep ocean world with Gardens of glass island at the water level. can i do that in the config. i have changed all the types except grass to false and edited the island y level but i cant set the world to deep ocean i have tried to change the "biome used for entire world" but that just crashed my game when creating the world. Any help would be welcomed, if this is not possible in the config sorry to waste your time.  Thank you.

**Comment by Bartz24** [comment]
you'll have to change worldGenType to SUPERFLAT and put the superflat settings where there is water in the worldGenSpecialParameters

you should be able to set worldBiomeID to 24 (i think is deep ocean)
