### ISSUE TITLE
End - Portal doesn't spawn at correct height

### ISSUE THREAD

**Issue by marckskl** [Bartz24/VoidIslandControl#33]
Whenever I spawn into the End the first time, it spawns the bedrock portal in the void so that only 2 blocks appear above it but no portal. My end is void in the config. Using 1.3.3. Apparently 1.3.2 had this issue too. I tried other mods that made a void end and they worked so I ruled out anything else affecting it. Here's a picture to show you. The top of the portal sits usually at y=49, it sits at y=2 now. So the only way to get back is /island home but I believe this is considered a bug. [![Screenshot from Gyazo](https://gyazo.com/4f3e0bda9de2c4b91ff9afb3eae30b0c/raw)](https://gyazo.com/4f3e0bda9de2c4b91ff9afb3eae30b0c)

**Comment by Bartz24** [comment]
fixed for today's update
