### ISSUE TITLE
Custom World Preset String

### ISSUE THREAD

**Issue by Boolyman** [Bartz24/VoidIslandControl#37]
Is there any way to use a custom world preset string with void islands, instead of just the Flatworld type?  For example, I am trying to do a completely oceanic world, and the islands will spawn in the water with a dome around them.  I am able to do this fine with superflat world type, putting the preset string in the configs.  However, the extremely flat ocean bottom looks very artificial... and the only other options seem to be VOID or OVERWORLD.  Is there any way to use a customized worldgen string?

**Comment by Bartz24** [comment]
there is a single biome id you can set to an ocean biome, and when the world type config is set to OVERWORLD it'll generate ocean biomes

**Comment by Boolyman** [comment]
But I need to be able to customize the sea level, which you can't do with normal overworld generation unless you use the Customize world option.

**Comment by Bartz24** [comment]
Ah ok. I can add a sea level config.

**Comment by Bartz24** [comment]
Decided to add the customized world type config in 1.3.6

**Comment by Boolyman** [comment]
Awesome thank you so much!

**Comment by Boolyman** [comment]
I have been trying to use this, but I keep getting the message "You are not in a void world type" when I try to use a customized world generation.  Do I need to change something in particular in the config file to make this work?
