### ISSUE TITLE
No option to disable protection v1.3.6

### ISSUE THREAD

**Issue by marckskl** [Bartz24/VoidIslandControl#38]
Can we have a config option to disable protection? I have a small amount of people on a private server that now i can't go to their bases because of the protection. I don't see a way to turn it off.

**Comment by ghost** [comment]
I agree with this cause I have a public server that because the protections are active, Players now get spammed with You can't be away from your island or spawn that far away. This is happening with the new update.

**Comment by Bartz24** [comment]
Added this config in 1.3.8 (it was called something different in 1.3.7)
