### ISSUE TITLE
Starting inv ERROR

### ISSUE THREAD

**Issue by YOYOK9** [Bartz24/VoidIslandControl#4]
How does the Starting inv work exactly I currently have this 
startinginv {
    # The starting inventory Format: modid:itemid:meta*amt (All parameters required) [default: [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
    S:"Starting Inventory" <
        [default: [claybucket:claybucket:2],
        [claybucket:claybucket:1],
        [minecraft:bread]*16]
}
But when I start an island I get:
Error getting starting inventory.\njava.lang.ArrayIndexOutOfBoundsException: 2

Is there something I'm missing? Or a tutorial somewhere or something i could look at?

**Comment by Bartz24** [comment]
```
S:"Starting Inventory" <
claybucket:claybucket:2*1
claybucket:claybucket:1*1
minecraft:bread:0*16


LEAVE THE BLANK SPACES
>
```

Get rid of [] ,
Make sure you follow the format modid:itemid:meta*amt
**All parameters are required**


You can also use the in-game mod options for editing the list.
