### ISSUE TITLE
Adventure mode instead of teleportation

### ISSUE THREAD

**Issue by heke85** [Bartz24/VoidIslandControl#40]
https://github.com/Bartz24/VoidIslandControl/blob/07d580c6a7844a0e9532dc73dcec0d27e98bc33b/src/main/java/com/bartz24/voidislandcontrol/EventHandler.java#L140

Hello, I am from Germany.
Maybe you could change that so that you are not teleportiert but is in the adventure mode offset?

**Comment by TheLimePixel** [comment]
The point of it is so you can't interact with the machines and chests on the island. In adventure mode, you can do that.

**Comment by heke85** [comment]
and if this would be optional to adjust?
then can i decide this yourself

**Comment by Bartz24** [comment]
The protection issue has been fixed.

The visit command, which now works in version 1.3.8, can be used instead of going into adventure mode
