### ISSUE TITLE
Structure Blocks Dissappear on Island Generation

### ISSUE THREAD

**Issue by Boolyman** [Bartz24/VoidIslandControl#43]
I am using a custom island which has a few vanilla structure blocks built into it that the player can later activate for different purposes.  For some reason when the Void Island spawns, all of those blocks are missing.  I have used the structure blocks before with mods like World Primer and Recurrent Complex, and did not have this issue.  Is there something in Void Island Control that prevents the starting islands from having structure blocks in them?  They don't activate on spawn or anything fancy like that, so Im not sure why there would be an issue.

**Comment by Bartz24** [comment]
Fixed in 1.3.9
