### ISSUE TITLE
Respawn below platform

### ISSUE THREAD

**Issue by SimonMeskens** [Bartz24/VoidIslandControl#49]
It seems like spawn point is not correctly set to the /home location. I'm using a custom island, where the data structure block is 10 blocks high in the structure and I'm respawning 10 blocks too low when I respawn. This means I keep dying to the void endlessly

**Comment by SimonMeskens** [comment]
Just out of curiosity, I set the custom island as the main (0,0) island and it does indeed spawn me below the platform from the get-go. It doesn't seem to respect the Y offset for the data structure block when generating the island.

**Comment by SimonMeskens** [comment]
I did some more testing and it seems like your spawn point is always 2 blocks above the bottom of the structure, so it does ignore the data structure block completely for setting spawn

**Comment by KonradStuewe** [comment]
I can confirm this. I have set the custom island as the 0,0 island and when I generate the world I spawn under the island. Didn't find a way yet to get around this.

**Comment by Bartz24** [comment]
Should be fixed for 1.5.0
