### ISSUE TITLE
Starting inventory issue

### ISSUE THREAD

**Issue by Winddbourne** [Bartz24/VoidIslandControl#5]
I can't seem to get the starting inventory to work. It errors out every time.  Here are some things I've tried:

startinginv {
    # The starting inventory Format: modid:itemid:meta*amt (All parameters required) [default: [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
    S:"Starting Inventory" <minecraft:torch:0*1>
}

startinginv {
    # The starting inventory Format: modid:itemid:meta*amt (All parameters required) [default: [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
    S:"Starting Inventory" <[minecraft:torch:0*1]

>
}

What am I doing wrong?

**Comment by Bartz24** [comment]
```
S:"Starting Inventory" <
        minecraft:torch:0*1
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
     >
```

leave the blank spaces and put it on the next line

a command will be added to set the config in game

**Comment by Winddbourne** [comment]
Good idea. I never would have guessed that I needed to skip down a line and indent it like that. Thanks for the quick reply.
