### ISSUE TITLE
when leaving the island to change to a different island you loose all your inventory

### ISSUE THREAD

**Issue by raziel23x** [Bartz24/VoidIslandControl#50]
just as teh title says i looked at the cfg file and cannot find any thing to turn this off so that you do not loose whats in your inventory when you leave a group island or want to change your starter island or is ther e a work around to this

**Comment by ghost** [comment]
In the config check line 107/108; That's the one that resets inventory upon creation of a new island

**Comment by raziel23x** [comment]
its already set to false yet it still clears inventory

**Comment by Bartz24** [comment]
Will be fixed for 1.5.0
