### ISSUE TITLE
Delete all island contents on reset

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Bartz24/VoidIslandControl#51]
Is there either:
A permission to deny players resetting their island
A way to delete ALL contents of a players island should they /island reset

I am running a server, where homes are enabled and players are able to set homes and go back to their old islands and still be able to build etc. 
Setting the config to not allow people to leave their islands means trading and visiting is impossible, while not in creative mode.

**Comment by Bartz24** [comment]
The only way to prevent islands from being reset is turning off allowIslandCreation and turning on autoCreate.
Deleting islands isn't possible because when it was in, it would time out servers. Still working on a way to do this efficiently.
