### ISSUE TITLE
Spawn island does not respect custom spawn points

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Bartz24/VoidIslandControl#57]
I created a custom island and added it to my modpack. When I create a new island and choose my custom island type, it works flawlessly. I spawn exactly where I placed the structure block.

However, I also tried changing this config setting so the custom island would appear at spawn:

`S:islandMainSpawnType=jungle_star`

When I do this, the player doesn't appear at spawn like I intend. Instead they appear off to one side and fall into the void. The structure block set to "spawn_point" has no effect.

**Comment by Bartz24** [comment]
fixed in the coming 1.5.1 version
