### ISSUE TITLE
Suggestion: Ignore `protectionBuildRange` in singleplayer

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Bartz24/VoidIslandControl#58]
In multiplayer, being able to create multiple islands is a fantastic feature. In singleplayer, it ends up being unnecessarily restrictive. While in singleplayer, it makes sense for players to be able to build well outside of the limit normally enforced by the `protectionBuildRange` config entry.

**Comment by Bartz24** [comment]
1.5.1 will only check for protection build range if there is more than 1 island (aside from the main spawn)
