### ISSUE TITLE
It looks like the pumpkins and the blocks beneath them aren't spawning on the snow island

### ISSUE THREAD

**Issue by Winddbourne** [Bartz24/VoidIslandControl#6]
![2017-02-01_22 09 33](https://cloud.githubusercontent.com/assets/24589533/22535801/7dcd44d8-e8cb-11e6-8040-dec10747e4ef.png)

I've included this picture file. Not sure why it's happening but when I went to test out my new torch in the inventory I landed randomly on a snow island and there were two blank spots where the pumpkins are supposed to be. 

It certainly isn't game breaking for me, but I figured you'd want to know about it. In my settings the bedrock is replaced with the filler block if that helps you isolate what is going on here. :)

**Comment by Bartz24** [comment]
oh...since there's 2 snow blocks and a pumpkin on top...snow golems spawn xD
changing bottom block to ice :P
