### ISSUE TITLE
How to remove Magma Island

### ISSUE THREAD

**Issue by InnuendoSA** [Bartz24/VoidIslandControl#61]
Hi
I use your mod on my server because of how well its setup.
The only thing I cant get rid of is the magma Island.
Is it a bug? 
Missing config settings.
Or did one of my Admins  cause this?
Thanks
InnuendoSA

**Comment by Bartz24** [comment]
the magma island is added by Sky Resources 2.

there is an option in the config for Sky Resources 2 to remove the magma island

**Comment by InnuendoSA** [comment]
Thanks!
