### ISSUE TITLE
version 1.5.1 islands are generating without bedrock underneath

### ISSUE THREAD

**Issue by Saereth** [Bartz24/VoidIslandControl#64]
after updating to 1.5.1 newly created islands no longer have bedrock under them, our config settings are:

        # Type of block to spawn under islands
        # Valid values:
        # BEDROCK
        # SECONDARYBLOCK
        S:bottomBlockType=BEDROCK

using a custom island:
https://imgur.com/a/UNESFoc

before the update this generated with a single bedrock below it and now it no longer does

**Comment by Bartz24** [comment]
That config only applies to the default islands... if you want bedrock on your custom island put it in yourself!

**Comment by Saereth** [comment]
oh so It was a bug that it was there in the previous version? ok np!

**Comment by Bartz24** [comment]
honestly i don't remember anything about bedrock showing up on custom islands like that...but i guess it's fixed? works for me...
