### ISSUE TITLE
Option to disable leave/join island when you enable auto island generation

### ISSUE THREAD

**Issue by Winddbourne** [Bartz24/VoidIslandControl#7]
When we turn on automatically creating islands it would be nice to be able to turn OFF leaving them and joining other islands. Without this feature we are likely to get people completely abandoning islands and leaving a lot of area that can't be claimed again and reused in multiplayer. This could obviously lead to tons of tiny 3X3 platforms littering the void with nothing but vast swathes of abyss between them. 

Being able to leave your island at will also can sometimes defeat a mod author's purpose in enabling auto island generation. For me this is true. There are a lot of options being included for co-op play, travel between islands, and even teleportation and portals of various sorts for forming communities but it is assumed that every player has their own space.

**Comment by Bartz24** [comment]
Added config, also changed invite and added join command to allow for this
