### ISSUE TITLE
Snow Island spawns in Desert Biome

### ISSUE THREAD

**Issue by xXJamieXx** [Bartz24/VoidIslandControl#8]
When the snow island spawns in a desert biome, it makes it impossible to play because the snow golem just dies because of the heat. At least thats what I gathered, I can't see any other reason why it would die.

Void Island Control version: 1.1.1
Sky Resources version: 1.5.6 (don't know if this matters)
Compact Layer version: 0.2.2 (don't know if this matters)

**Comment by Bartz24** [comment]
Fixed for next version
